### ISSUE TITLE
Fehlerfälle in der App behandeln

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#1]
@Nunay 
In der App muss das Exception-Handling implementiert werden.
Dazu kann der Code der RestApiClient-Klasse übernommen werden. Dabei muss die **getMessage**()-Methode verwendet werden, um die Message aus dem ankommenden JSON-Text zu extrahieren.
Die Client-Klasse: https://github.com/Kassensystem/DatabaseSystem/blob/master/src/main/java/dhbw/sa/kassensystem_rest/restApi/client/RestApiClient.java
Davon die getMessage-Methode verwenden:

```
/**
  * Extrahiert die Fehlermessage aus dem Body der JSON-Rückmeldung
  * @param body body der Rückmeldung des RestApiContorllers in JSON   
  * @return extrahierte Fehlermessage des RestApiControllers
  */
private static String getMessage(String body) {
        int lastindex = body.lastIndexOf("message");
        char [] charArray = body.toCharArray();
        int index = lastindex + 10;
        char newChar = charArray[index];
        StringBuilder message = new StringBuilder();
        while(!String.valueOf(newChar).equals("\"")) {
            message.append(newChar);
            newChar = charArray[++index];
        }
        return message.toString();
}
```

Übergeben werden muss der **komplette Body** der **ResponseEntity**. In der Client-Klasse findest du **Verwendungsbeispiele** dafür, wie z.B:

```
try {
            ResponseEntity<ArrayList<Order>> responseEntity =
                    restTemplate.exchange
                            (REST_SERVICE_URL + "/orders", HttpMethod.GET,
                                    null, new ParameterizedTypeReference<ArrayList<Order>>() {});

            return responseEntity.getBody();
}
catch (HttpClientErrorException e) {
            String message = getMessage(e.getResponseBodyAsString());
            throw new Exception(message);
}
```

Kurz zur **Funktion der getMessage()-Methode**:
Wenn beim Abfragen von Daten im Controller(Server) eine Exception auftritt, wird diese in der ResponseEntity anstatt der angefragten Daten geschickt. Im Client tritt dann eine **HttpClientErrorException** auf. Diese hat als Body im JSON-Format eine Beschreibung des Fehlers unter dem Attribut "message". Von der Position dieses Attributs ausgehend wird dann die Message anhand der darauffolgenden Anführungszeichen extrahiert.
Ist insgesamt umständlich gelöst, anders hab ich es mit angemessenem Zeitaufwand aber nicht gelöst bekommen.
Die extrahierte Message sollte dann in der Application in einer **Toast-Message** dargestellt werden.

**Comment by Nunay** [comment]
Haben wir jetzt anders gelöst.
Damit fällt getMessage() aus dem Code!
