### ISSUE TITLE
Creat/Update Order

### ISSUE THREAD

**Issue by Nunay** [Kassensystem/AndroidApplication#10]
Fehler Meldungen werden noch ausgegeben
Und es lassen sich so keine Orders anlegen

**Comment by Nunay** [comment]
wenn der Server **"ull"**  zurück gibt, gibt es dann einen Kommunikationsfehler oder an was könnte das liegen?
Fällt dir da spontan was ein?

**Comment by marvinmai** [comment]
Sorry, hab die Frage jetzt erst gesehen.
Habs gerade mal ausprobiert, der Server gibt als Fehlermeldung zurück, dass die Items nicht existieren, die der Order hinzugefügt wurden. Liegt daran, dass immer dieselben Items ausgewählt werden und nicht extrahiert wird, welche Items ausgewählt wurden. Zumindest bei mir. Habe dann die Items entsprechend angelegt, dass alle IDs existieren und dann klappts mit dem erzeugen einer Order.

**Comment by Nunay** [comment]
Funktioniert.
Lag an fehlendem Print-Service
