### ISSUE TITLE
Im Spinner wird immer "Bitte wählen:" als Eintrag angezeigt

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#11]

**Comment by Nunay** [comment]
Des ist kein bug, sondern gewollt:)

Weil sonst wird der Tisch nicht ausgewählt, wenn man den ersten Tisch nimmt, aber nicht auswählt.
Könnte man auch anders lösen, aber ich fand das eigentlich eine gute Lösung.

**Comment by Nunay** [comment]
"Gelöst" mit leerem String.
