### ISSUE TITLE
Auslesen des HTTP-Headers

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#16]
@Nunay 
Ich habe gerade mal danach schauen wollen, wie wir nochmal genau in der App den Header ausgelesen haben. Bin ich zu blöd das zu finden oder hast du das noch nicht commited? Müsste glaube ich die Stelle im Code sein, oder?
https://github.com/Kassensystem/AndroidApplication/blob/d2c8ff57f572275ffa7ee997ec285e1327f4475b/app/src/main/java/dhbw/sa/kassensystemapplication/fragment/ItemSelect.java#L447

Edit: Habe vorher "beschreiben" statt "auslesen" geschrieben. Hab ich durcheinander gebracht.

**Comment by Nunay** [comment]
https://github.com/Kassensystem/AndroidApplication/blob/16f696445981936886695e16e6077a07d633d88d/app/src/main/java/dhbw/sa/kassensystemapplication/fragment/TableSelection.java#L334

Sowohl als auch wies aussieht :) Das sollte die stelle sein die du meintest:)
