### ISSUE TITLE
gelöschtes Item bleibt in Bestellung

### ISSUE THREAD

**Issue by Nunay** [Kassensystem/AndroidApplication#19]
In Arraylist orderedItems

**Comment by Nunay** [comment]
https://github.com/Kassensystem/AndroidApplication/blob/492b1eb828e2d693331b0edfc0594ced4e063de0/app/src/main/java/dhbw/sa/kassensystemapplication/fragment/ItemSelect.java#L411

Fehler vermutlich gefunden und behoben
Aber noch überprüfen mit richtiger DB Struktur

**Comment by Nunay** [comment]
Da müssen wir am Montag nochmal zusammen schauen.
Ich bin mal mit dem Debugger auf beide Seiten gegangen, und von der App werden die richtige Anzahl von OrderedItems verschickt in der ArrayList. Es kommt auch die richtige größe der ArrayList auf der Controller Seite 

Aber das seltsame ist, das genau die gelöschte Anzahl noch erhalten bleibt.

Wär gut wenn wir da dann am Montag nochmal zusammen drüber schauen.

**Comment by marvinmai** [comment]
Okay, seltsam. Das kann ja eigentlich nicht sein. :D 
Klar, schauen wir uns Montag mal an.

**Comment by marvinmai** [comment]
@Nunay 
Hab das gerade mal getestet, es scheint richtig zu funktionieren.
Wenn ich den Artikel wieder rausnehme, wird er auch nicht übertragen.

**Comment by Nunay** [comment]
Behoben
