### ISSUE TITLE
Formatierung der Anzeige Bestellübersicht fehlerhaft

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#28]
Die Anzeige der Summe passt bei mir nicht:

![screenshot_20180318-163913 1](https://user-images.githubusercontent.com/29154212/37567855-3a5d4d8e-2acd-11e8-9da0-b3622ed6d218.png)

**Comment by marvinmai** [comment]
Ab einer dreistelligen Zahl überlappen sich auch Anzahl und Name des Artikels. Frage ist nur, wie häufig das in der Praxis vorkommt.

![screenshot_20180318-171740 1](https://user-images.githubusercontent.com/29154212/37568064-6bd47ff6-2ad0-11e8-859d-21144f90a72e.png)

**Comment by Nunay** [comment]
Zu erstens: sollte behoben sein.
Zu zweitens: ich pass es jetzt mal nicht an  weil ich das für einen sehr unwahrscheinlichen Fall halte. 
Weil dann kann man auch noch den Fall von 4 oder 5 Stellig betrachten was in meinen Augen keinen Sinn macht:)
