### ISSUE TITLE
Dialog "Passwort bearbeiten"

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#30]
Soweit ich weiß, war doch eigentlich geplant, dass das Passwort nur im DB-Manager bearbeitet wird, oder nicht? Da habe ich jetzt keine Schnittstelle für implementiert. Wäre aber machbar, wo du die Seite jetzt schon mit drin hast.

**Comment by Nunay** [comment]
Ich habs mal eingebaut, weil der Moosheimer das ja so wollte.
Aber wenn wirs nicht implementieren kann ich es auch raus lassen. Ist mir prinzipell egal:)
können wir gerne morgen nochmals bereden

**Comment by Nunay** [comment]
implementiert
