### ISSUE TITLE
Idee: Preis der Artikel in der Artikel-Ansicht mit anzeigen

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#31]
Wäre evtl. sinnvoll, um auf Nachfrage dem Kunden das sagen zu können. Wäre dann noch mehr wie eine digitale Speisekarte.
Platz ist auf der Seite auf noch genug.
Was meinst du?

**Comment by Nunay** [comment]
Ich bin unschlüssig. Würde das dann aber ehrlich gesagt eher in die Seite einbauen, in der man den Artikeln kommentare hinzufügen kann.

**Comment by Nunay** [comment]
eingebaut
