### ISSUE TITLE
Fehler beim Anlegen einer Bestellung nachdem diese bezahlt wurde

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#37]
Nachdem eine Bestellung bezahlt wurde und eine neue Bestellung für den Tisch angelegt werden soll, bleibt die App bei der Auswahl des Tisches hängen. Keine Fehlermeldung, es passiert einfach nichts.
Das ist bei aber nicht immer passiert, sondern scheinbar sporadisch.

**Comment by Nunay** [comment]
Hab den Fehler nicht reproduzieren können, hab aber die App nochmals überarbeitet, weil mir da jetzt aufgefallen ist das ich da totalen "schwachsinn" gemacht hatte. Also eine sehr sehr umständliche lösung. Keine ahnung warum mir das damals nicht eingefallen ist.

Jetzt habe ich es aufjedenfall verbessert. (falls du dich noch erinnern kannst: wenn man schnell 2 mal auf einen Button geklickt hat ist die App abgestürzt. Um dieses Problem ging es)
Vielleicht hat die Verbesserung den Fehler behoben. Kann ich mir zwar nicht Vorstellen, da er nur sporadisch auftritt, aber ich weiß es nicht.

Ich werde Herr Moosheimer dann jetzt schreiben das der Fehler für uns nicht reproduzierbar war, und er vielleicht mal alle Daten löschen soll. 
Und die neue Version der App verwenden soll.

Wenn das nichts bringt würde ich vorschlagen das wir uns mit ihm nach den Prüfungen nochmal in Verbindung setzen. Wieder über ein Team Viewer Meeting.
Wenn du das auch so sehen würdest, dann würde ich die Mail so schreiben. Falls noch fragen hast, schreib mir oder ruf mich an:) hoff das ich es diesmal hör :D

**Comment by marvinmai** [comment]
Schließe ich dann mal, scheint ja dann behoben worden zu sein. Nicht, dass unsere Nachfolger denken, wir haben hier Bugs nicht behoben. :D
