### ISSUE TITLE
Bestand eines Artikels hinzufügen

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#4]
Der aktuelle Bestand eines Artikels muss in der Übersicht der Artikel angezeigt werden. Beim Betätigen der Plus-/Minus-Buttons soll entsprechend die Anzahl erhöhrt/verringert werden.
Anzahl soll zwischen dem Artikelnamen und den Buttons angeordnet sein.

**Comment by Nunay** [comment]
Erledigt. Wenn der Bestand auf 0 ankommt, kann auch kein weiterer Artikel mehr bestellt werden
