### ISSUE TITLE
Rest-URL einstellbar machen

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#5]

**Comment by Nunay** [comment]
Ich hab jetzt den  URL austauschbar gemacht.

Ich hoffe ich hab alle "Klassen" hochgeladen. Also vorallem die XML Dateien.

**Comment by marvinmai** [comment]
Ok, super! Wie sieht das in der App aus?

**Comment by marvinmai** [comment]
ach, hab den commit gerade gesehen. cool, dass der navigation drawer schon drin ist! :)
