### ISSUE TITLE
Navigation Drawer anpassen, Activites und Fragments anpassen

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#7]
App design so anpassen, dass alle GUIs in Fragments angezeigt werden. 
Siehe: 
https://github.com/marvinmai/NavigationTest
https://github.com/marvinmai/E-Smog-Meter

Toast message in einem Fragment:
```
Toast.makeText(getActivity(), message, Toast.LENGTH_SHORT).show();*/
```

**Comment by marvinmai** [comment]
@Nunay 
- [x] Speicher-Design entsprechend anpassen

**Comment by Nunay** [comment]
Fragments sind erstellt, funktionieren auch. Aber bis jetzt nur das Layout.
Funktion werde ich vllt gegen später oder morgen angehen

**Comment by Nunay** [comment]
Der speicher und das Layout wurden angepasst.

Allerdings lässt sich derzeit immer noch keine Order erstellen/updaten.
Dafür erstell ich aber ein neues issue
