### ISSUE TITLE
Exception-Handling implementieren

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/AndroidApplication#9]
- optional: globales Exception-Handling

**Comment by Nunay** [comment]
funktioniert jetzt eigentlich. aber ich warte noch bis ich die Creat und uppdate order hin bekommen habe. Dann schließ ich dieses issue

**Comment by marvinmai** [comment]
Als Toast message werden aber immer noch keine Fehlermeldungen angezeigt, auch nicht die vom Controller. Sollte das schon funktionieren?

**Comment by Nunay** [comment]
Bei mir hat es eigentlich geklappt. Also habs jetzt nur mit einer probiert. 
Mit der Fehlermeldung, dass keine Verbindung zur Datenbank hergestellt werden konnte.

**Comment by Nunay** [comment]
Funktioniert soweit.
